# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
# Configure Using Gemfile
# gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Neapolitan_Dev

test:
  <<: *default
  database: Neapolitan_Test

production:
  <<: *default
  database: Neapolitan_P
  username: 
  password: 
